//  Copyright © 2021 650 Industries. All rights reserved.

NS_ASSUME_NONNULL_BEGIN

// do not modify this file - generated by scripts/generate-tests.js

// GENERATED CONSTANTS BEGIN

// GENERATED CONSTANTS END

@interface EXStructuredHeadersTestFixtures : NSObject

@end

NS_ASSUME_NONNULL_END
